KNOWN_LANGUAGES = {
    ".py": "Python",
    ".pyx": "Python",
    ".pyi": "Python",
    ".js": "JavaScript",
    ".jsx": "JavaScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".java": "Java",
    ".kt": "Kotlin",
    ".kts": "Kotlin",
    ".scala": "Scala",
    ".groovy": "Groovy",
    ".c": "C",
    ".h": "C",
    ".cpp": "C++",
    ".cc": "C++",
    ".cxx": "C++",
    ".hpp": "C++",
    ".hxx": "C++",
    ".hh": "C++",
    ".cs": "C#",
    ".m": "Objective-C",
    ".mm": "Objective-C++",
    ".html": "HTML",
    ".htm": "HTML",
    ".xhtml": "HTML",
    ".css": "CSS",
    ".scss": "SCSS",
    ".sass": "Sass",
    ".less": "Less",
    ".vue": "Vue",
    ".svelte": "Svelte",
    ".rb": "Ruby",
    ".erb": "Ruby",
    ".rake": "Ruby",
    ".gemspec": "Ruby",
    ".go": "Go",
    ".rs": "Rust",
    ".php": "PHP",
    ".phtml": "PHP",
    ".swift": "Swift",
    ".sh": "Shell",
    ".bash": "Shell",
    ".zsh": "Shell",
    ".fish": "Shell",
    ".ps1": "PowerShell",
    ".json": "JSON",
    ".yaml": "YAML",
    ".yml": "YAML",
    ".xml": "XML",
    ".toml": "TOML",
    ".md": "Markdown",
    ".markdown": "Markdown",
    ".rst": "reStructuredText",
    ".tex": "TeX",
    ".sql": "SQL",
    "Dockerfile": "Dockerfile",
    ".cmake": "CMake",
    "Makefile": "Makefile",
    ".asm": "Assembly",
    ".s": "Assembly",
    ".ex": "Elixir",
    ".exs": "Elixir",
    ".erl": "Erlang",
    ".hs": "Haskell",
    ".lua": "Lua",
    ".pl": "Perl",
    ".pm": "Perl",
    ".r": "R",
    ".rmd": "RMarkdown",
    ".dart": "Dart",
    ".jl": "Julia",
    ".zig": "Zig",
    ".cr": "Crystal",
    ".nim": "Nim",
    ".fs": "F#",
    ".fsx": "F#",
    ".clj": "Clojure",
    ".cljs": "Clojure",
    ".cljc": "Clojure",
    ".lisp": "Common Lisp",
    ".lsp": "Common Lisp",
    ".f": "Fortran",
    ".f90": "Fortran",
    ".f95": "Fortran",
    ".sol": "Solidity",
}

IGNORED_DIRS = {
    ".git",
    ".svn",
    ".hg",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".tox",
    ".venv",
    "venv",
    "env",
    "virtualenv",
    "lib",
    "lib64",
    "include",
    "dist",
    "build",
    "egg-info",
    "pip-wheel-metadata",
    ".eggs",
    "node_modules",
    ".next",
    ".nuxt",
    ".output",
    "out",
    ".cache",
    "bower_components",
    "target",
    ".gradle",
    ".mvn",
    "cmake-build",
    ".vs",
    "vendor",
    ".bundle",
    ".idea",
    ".vscode",
    ".settings",
    ".eclipse",
    "bin",
    "obj",
    "release",
    "debug",
    ".npm",
    ".yarn",
    ".pnpm-store",
    ".cargo",
    "coverage",
    "htmlcov",
    ".coverage",
    "test-results",
    ".serverless",
    ".terraform",
    "logs",
    "tmp",
    "temp",
}

IGNORED_EXTENSIONS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".svg",
    ".bmp",
    ".ico",
    ".webp",
    ".tiff",
    ".psd",
    ".mp4",
    ".avi",
    ".mov",
    ".wmv",
    ".flv",
    ".mkv",
    ".mp3",
    ".wav",
    ".ogg",
    ".flac",
    ".aac",
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".iml",
    ".class",
    ".jar",
    ".war",
    ".ear",
    ".o",
    ".obj",
    ".a",
    ".lib",
    ".zip",
    ".tar",
    ".gz",
    ".bz2",
    ".xz",
    ".7z",
    ".rar",
    ".tgz",
    ".iso",
    ".txt",
    ".md",
    ".pdf",
    ".doc",
    ".docx",
    ".xls",
    ".xlsx",
    ".ppt",
    ".pptx",
    ".odt",
    ".rtf",
    ".csv",
    ".log",
    ".db",
    ".sqlite",
    ".sqlite3",
    ".mdb",
    ".accdb",
    ".ttf",
    ".otf",
    ".woff",
    ".woff2",
    ".eot",
    ".lock",
    ".cache",
    ".tmp",
    ".temp",
    ".swp",
    ".swo",
    ".bin",
    ".dat",
    ".data",
    ".dump",
}